services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - school-net

  backend:
    build: ./api-gateway
    container_name: unified-backend
    ports:
      - "4000:4000"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - school-net
    environment:
      - MONGO_URI=mongodb://mongodb:27017/csn
      - NODE_ENV=production
      - RABBIT_URL=amqp://rabbitmq:5672

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - school-net

